#!/usr/bin/env python3
import os
import re

# --- Ajustado a TU proyecto ---
ASSETS_PREFIX_IN_DATA = "assets/carousel"   # lo que guardamos en simpsons.js (strings)
PROJECT_ROOT_FROM_HERE = "../.."            # estando en assets/carousel -> subimos a raíz

SIMpsons_JS_OUT = os.path.join(PROJECT_ROOT_FROM_HERE, "src", "data", "simpsons.js")
IMAGES_MAP_JS_OUT = os.path.join(PROJECT_ROOT_FROM_HERE, "src", "assets", "imagesMap.js")

# Desde src/assets/imagesMap.js hasta assets/carousel:
# src/assets -> ../../assets/carousel/
REQUIRE_PREFIX_FROM_IMAGESMAP = "../../assets/carousel/"
# --------------------------------

episode_re = re.compile(r"^(\d{1,2})x(\d{1,2})\.jpg$", re.IGNORECASE)
season_icon_re = re.compile(r"^Season_(\d{1,2})_(Icon|icon)\.jpg$", re.IGNORECASE)

def ensure_dir_for_file(filepath: str):
    dirpath = os.path.dirname(filepath)
    os.makedirs(dirpath, exist_ok=True)

def pad2(n: int) -> str:
    return str(n).zfill(2)

def js_string(obj, indent=2):
    """
    Convierte dict/list a un string JS "bonito" sin depender de json,
    manteniendo comillas dobles y escapes razonables.
    """
    import json
    return json.dumps(obj, ensure_ascii=False, indent=indent)

def write_simpsons_js(seasons, out_file):
    ensure_dir_for_file(out_file)
    content = []
    content.append("// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.\n")
    content.append("// Generated by assets/carousel/generate_simpsons_json.py\n\n")
    content.append("const data = ")
    content.append(js_string({"seasons": seasons}, indent=2))
    content.append(";\n\n")
    content.append("export default data;\n")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("".join(content))

def write_images_map_js(image_filenames, out_file, require_prefix):
    ensure_dir_for_file(out_file)

    unique = sorted(set(image_filenames), key=lambda s: s.lower())

    lines = []
    lines.append("// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.\n")
    lines.append("// Generated by assets/carousel/generate_simpsons_json.py\n\n")
    lines.append("export const imagesMap = {\n")
    for fname in unique:
        lines.append(f'  "{fname}": require("{require_prefix}{fname}"),\n')
    lines.append("};\n\n")
    lines.append("export function resolveAsset(pathStr) {\n")
    lines.append("  if (!pathStr) return undefined;\n")
    lines.append("  const parts = String(pathStr).split('/');\n")
    lines.append("  const filename = parts[parts.length - 1];\n")
    lines.append("  return imagesMap[filename];\n")
    lines.append("}\n")

    with open(out_file, "w", encoding="utf-8") as f:
        f.writelines(lines)

def main():
    files = os.listdir(".")

    # iconos reales existentes (por ejemplo Season_30_icon.jpg)
    season_icon_by_number = {}
    for f in files:
        m = season_icon_re.match(f)
        if m:
            season_num = int(m.group(1))
            season_icon_by_number[season_num] = f

    seasons_map = {}
    all_images_for_map = []

    # Añadir iconos al map (solo los que existan)
    for season_num, icon_file in season_icon_by_number.items():
        all_images_for_map.append(icon_file)

    # Episodios
    for f in files:
        m = episode_re.match(f)
        if not m:
            continue

        season_num = int(m.group(1))
        ep_num = int(m.group(2))

        all_images_for_map.append(f)

        if season_num not in seasons_map:
            default_icon = f"Season_{season_num}_Icon.jpg"
            real_icon = season_icon_by_number.get(season_num, default_icon)

            # Si el icono "default" no existe en disco pero hay real -> ok
            # Si no existe ninguno, igualmente dejamos el string (por si luego lo añades)
            seasons_map[season_num] = {
                "id": season_num,
                "title": f"Temporada {season_num}",
                "image": real_icon,
                "episodes": []
            }

            # Si ese icono existe realmente, lo mapeamos; si no, no lo añadimos al map
            if real_icon in files:
                all_images_for_map.append(real_icon)

        seasons_map[season_num]["episodes"].append({
            "id": f"{season_num}x{pad2(ep_num)}",
            "episodeNumber": ep_num,
            "title": "unknown",
            "duration": "unknown",
            "airDate": "unknown",
            "image": f
        })

    # ordenar temporadas/episodios
    seasons = [seasons_map[k] for k in sorted(seasons_map.keys())]
    for s in seasons:
        s["episodes"].sort(key=lambda e: e["episodeNumber"])

    # 1) simpsons.js
    write_simpsons_js(seasons, SIMpsons_JS_OUT)

    # 2) imagesMap.js
    write_images_map_js(all_images_for_map, IMAGES_MAP_JS_OUT, REQUIRE_PREFIX_FROM_IMAGESMAP)

    total_eps = sum(len(s["episodes"]) for s in seasons)
    print("OK -> generado", SIMpsons_JS_OUT)
    print("OK -> generado", IMAGES_MAP_JS_OUT)
    print("Temporadas:", len(seasons))
    print("Capítulos totales:", total_eps)
    print("Imágenes mapeadas:", len(set(all_images_for_map)))

if __name__ == "__main__":
    main()
